apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eduvoyage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: eduvoyage.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: eduvoyage-backend
                port:
                  number: 8080
          - path: /v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: eduvoyage-backend
                port:
                  number: 8080
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: eduvoyage-backend
                port:
                  number: 8080
          - path: /swagger-ui.html
            pathType: Exact
            backend:
              service:
                name: eduvoyage-backend
                port:
                  number: 8080
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: eduvoyage-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eduvoyage-frontend
                port:
                  number: 80
